In [19]:
import numpy as np
digits = np.array(range(10))
digits

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
digits.shape


(10,)

In [7]:
digits.dtype

dtype('int64')

In [10]:
np.log(digits+1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [13]:
len(dir(digits))


168

In [15]:
len(dir(np))

530

In [16]:
digits+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.sin(digits)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [22]:
digits.mean()

np.float64(4.5)

In [23]:
digits+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
nums = np.arange(100).reshape(20,5)
nums

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [27]:
nums.transpose()

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75,
        80, 85, 90, 95],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76,
        81, 86, 91, 96],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77,
        82, 87, 92, 97],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78,
        83, 88, 93, 98],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79,
        84, 89, 94, 99]])

In [28]:
nums.mean()

np.float64(49.5)

In [34]:
nums.mean(axis=1, keepdims=True)

array([[ 2.],
       [ 7.],
       [12.],
       [17.],
       [22.],
       [27.],
       [32.],
       [37.],
       [42.],
       [47.],
       [52.],
       [57.],
       [62.],
       [67.],
       [72.],
       [77.],
       [82.],
       [87.],
       [92.],
       [97.]])

In [38]:
b = np.arange(70).reshape(7,5,2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]],

       [[50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69]]])

In [41]:
b.mean(axis=2)

array([[ 0.5,  2.5,  4.5,  6.5,  8.5],
       [10.5, 12.5, 14.5, 16.5, 18.5],
       [20.5, 22.5, 24.5, 26.5, 28.5],
       [30.5, 32.5, 34.5, 36.5, 38.5],
       [40.5, 42.5, 44.5, 46.5, 48.5],
       [50.5, 52.5, 54.5, 56.5, 58.5],
       [60.5, 62.5, 64.5, 66.5, 68.5]])

In [44]:
nums

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [42]:
nums[0]

array([0, 1, 2, 3, 4])

In [43]:
nums[[0,5,10]]

array([[ 0,  1,  2,  3,  4],
       [25, 26, 27, 28, 29],
       [50, 51, 52, 53, 54]])

In [45]:
nums[0:10]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [46]:
nums[:,0:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17],
       [20, 21, 22],
       [25, 26, 27],
       [30, 31, 32],
       [35, 36, 37],
       [40, 41, 42],
       [45, 46, 47],
       [50, 51, 52],
       [55, 56, 57],
       [60, 61, 62],
       [65, 66, 67],
       [70, 71, 72],
       [75, 76, 77],
       [80, 81, 82],
       [85, 86, 87],
       [90, 91, 92],
       [95, 96, 97]])

In [47]:
nums%2

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [49]:
#select all columns for 15th row

nums[15]

array([75, 76, 77, 78, 79])

In [50]:
#select the third amd 5th columns for 9th row


nums[9,[2,4]]

array([47, 49])

In [51]:
nums%2==0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [52]:
nums[nums%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [54]:
nums[nums.sum(axis=1)<100]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [55]:
nums.sum(axis=1)<100


array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [56]:
(nums[nums%2==0]).shape

(50,)

In [58]:
nums.mean(axis=0)>50

array([False, False, False,  True,  True])

In [60]:
nums[:,nums.mean(axis=0)>50]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24],
       [28, 29],
       [33, 34],
       [38, 39],
       [43, 44],
       [48, 49],
       [53, 54],
       [58, 59],
       [63, 64],
       [68, 69],
       [73, 74],
       [78, 79],
       [83, 84],
       [88, 89],
       [93, 94],
       [98, 99]])

In [67]:
np.add(nums, 5, where=(nums%5==0))

array([[  5,   1,   2,   3,   4],
       [ 10,   1,   2,   3,   4],
       [ 15,   1,   2,   3,   4],
       [ 20,   1,   2,   3,   4],
       [ 25,   1,   2,   3,   4],
       [ 30,   1,   2,   3,   4],
       [ 35,   1,   2,   3,   4],
       [ 40,   1,   2,   3,   4],
       [ 45,   1,   2,   3,   4],
       [ 50,   1,   2,   3,   4],
       [ 55,   1,   2,   3,   4],
       [ 60,   1,   2,   3,   4],
       [ 65,   1,   2,   3,   4],
       [ 70,   1,   2,   3,   4],
       [ 75,   1,   2,   3,   4],
       [ 80,   1,   2,   3,   4],
       [ 85,   1,   2,   3,   4],
       [ 90,   1,   2,   3,   4],
       [ 95,   1,   2,   3,   4],
       [100,   1,   2,   3,   4]])

In [68]:
np.add(nums, 5, where=(nums%2==0))

array([[  5,   1,   7,   1,   9],
       [  1,  11,   1,  13,   1],
       [ 15,   1,  17,   1,  19],
       [  1,  21,   1,  23,   1],
       [ 25,   1,  27,   1,  29],
       [  1,  31,   1,  33,   1],
       [ 35,   1,  37,   1,  39],
       [  1,  41,   1,  43,   1],
       [ 45,   1,  47,   1,  49],
       [  1,  51,   1,  53,   1],
       [ 55,   1,  57,   1,  59],
       [  1,  61,   1,  63,   1],
       [ 65,   1,  67,   1,  69],
       [  1,  71,   1,  73,   1],
       [ 75,   1,  77,   1,  79],
       [  1,  81,   1,  83,   1],
       [ 85,   1,  87,   1,  89],
       [  1,  91,   1,  93,   1],
       [ 95,   1,  97,   1,  99],
       [  1, 101,   1, 103,   1]])

In [ ]:
np.add(nums, 5, where=(nums%5==0))

In [62]:
np.mod(nums, 2)

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [65]:
np.logical_and(nums, 2)

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [70]:
np.logical_and(nums, nums %2 ==0)

array([[False, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [71]:
np.logical_and?

Call signature:  np.logical_and(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'logical_and'>
File:            c:\users\benedict.hartmann\appdata\local\programs\python\python310\lib\site-packages\numpy\__init__.py
Docstring:      
logical_and(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Compute the truth value of x1 AND x2 element-wise.

Parameters
----------
x1, x2 : array_like
    Input arrays.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broad

In [72]:
np.greater(nums, 10)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [74]:
np.ceil(nums/3)

array([[ 0.,  1.,  1.,  1.,  2.],
       [ 2.,  2.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  5.,  5.],
       [ 5.,  6.,  6.,  6.,  7.],
       [ 7.,  7.,  8.,  8.,  8.],
       [ 9.,  9.,  9., 10., 10.],
       [10., 11., 11., 11., 12.],
       [12., 12., 13., 13., 13.],
       [14., 14., 14., 15., 15.],
       [15., 16., 16., 16., 17.],
       [17., 17., 18., 18., 18.],
       [19., 19., 19., 20., 20.],
       [20., 21., 21., 21., 22.],
       [22., 22., 23., 23., 23.],
       [24., 24., 24., 25., 25.],
       [25., 26., 26., 26., 27.],
       [27., 27., 28., 28., 28.],
       [29., 29., 29., 30., 30.],
       [30., 31., 31., 31., 32.],
       [32., 32., 33., 33., 33.]])

In [76]:
nums[np.greater(nums, 10)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
       62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
       79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
       96, 97, 98, 99])

In [77]:
nums[np.logical_and(nums, nums % 2 == 0)]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

PANDAS

In [78]:
import pandas as pd

In [83]:
df = pd.read_csv('transaction_data.csv')
df

Item_Description  Amount Traffic_Source Session_Duration
0            Notebook    20.0         Direct            3,470
1       Google Hoodie   124.0         Direct              401
2      Greeting Cards     6.0    Paid Search            2,608
3                 NaN     NaN            NaN            2,130
4             Lanyard     6.0         Direct            3,517
...               ...     ...            ...              ...
7391  Android T-Shirt    20.0       Referral            2,223
7392  Google Stickers     5.0    Paid Search            3,101
7393    Google Hoodie   124.0         Direct            2,107
7394    Google Hoodie   124.0   Social Media              919
7395    Google Hoodie   124.0    Paid Search               11

[7396 rows x 4 columns]

In [84]:
type(df['Amount'])

pandas.core.series.Series

In [85]:
songs = pd.Series([145,142,38,13], name = 'counts')

In [86]:
songs

0    145
1    142
2     38
3     13
Name: counts, dtype: int64

In [87]:
songs[2]

np.int64(38)

In [88]:
mask = songs > songs.median()

mask

0     True
1     True
2    False
3    False
Name: counts, dtype: bool

In [89]:
songs[mask]

0    145
1    142
Name: counts, dtype: int64

In [90]:
new_songs = pd.Series([54,83,26,90], name = 'counts')

In [91]:
songs + new_songs

0    199
1    225
2     64
3    103
Name: counts, dtype: int64

In [92]:
new_songs

0    54
1    83
2    26
3    90
Name: counts, dtype: int64

In [93]:
new_songs.add(songs)

0    199
1    225
2     64
3    103
Name: counts, dtype: int64

In [95]:
other_songs = pd.Series([54,83,26,90], name = 'new_counts', index = [3,2,1,0])
other_songs

3    54
2    83
1    26
0    90
Name: new_counts, dtype: int64

In [98]:
other_songs + new_songs #always matches the index first

0    144
1    109
2    109
3    144
dtype: int64

In [99]:
other_songs.add(new_songs)

0    144
1    109
2    109
3    144
dtype: int64

In [100]:
new_songs.add?

Signature: new_songs.add(other, level=None, fill_value=None, axis: 'Axis' = 0) -> 'Series'
Docstring:
Return Addition of series and other, element-wise (binary operator `add`).

Equivalent to ``series + other``, but with support to substitute a fill_value for
missing data in either one of the inputs.

Parameters
----------
other : Series or scalar value
level : int or name
    Broadcast across a level, matching Index values on the
    passed MultiIndex level.
fill_value : None or float value, default None (NaN)
    Fill existing missing (NaN) values, and any new element needed for
    successful Series alignment, with this value before computation.
    If data in both corresponding Series locations is missing
    the result of filling (at that location) will be missing.
axis : {0 or 'index'}
    Unused. Parameter needed for compatibility with DataFrame.

Returns
-------
Series
    The result of the operation.

See Also
--------
Series.radd : Reverse of the Addition operator, see
    `P

In [113]:
another_song_count = pd.Series([1,10,60 ], name = 'other_count')
another_song_count

0     1
1    10
2    60
Name: other_count, dtype: int64

In [115]:
new_songs.add(another_song_count, fill_value=0)

0    55.0
1    93.0
2    86.0
3    90.0
dtype: float64

In [118]:
(
    songs
    #add new songs
    .add(new_songs)
)


0    199
1    225
2     64
3    103
Name: counts, dtype: int64

In [120]:
songs.quantile()

np.float64(90.0)

In [121]:
songs.quantile?

Signature:
songs.quantile(
    q: 'float | Sequence[float] | AnyArrayLike' = 0.5,
    interpolation: 'QuantileInterpolation' = 'linear',
) -> 'float | Series'
Docstring:
Return value at the given quantile.

Parameters
----------
q : float or array-like, default 0.5 (50% quantile)
    The quantile(s) to compute, which can lie in range: 0 <= q <= 1.
interpolation : {'linear', 'lower', 'higher', 'midpoint', 'nearest'}
    This optional parameter specifies the interpolation method to use,
    when the desired quantile lies between two data points `i` and `j`:

        * linear: `i + (j - i) * (x-i)/(j-i)`, where `(x-i)/(j-i)` is
          the fractional part of the index surrounded by `i > j`.
        * lower: `i`.
        * higher: `j`.
        * nearest: `i` or `j` whichever is nearest.
        * midpoint: (`i` + `j`) / 2.

Returns
-------
float or Series
    If ``q`` is an array, a Series will be returned where the
    index is ``q`` and the values are the quantiles, otherwise
    a flo

In [135]:
(
    songs
    .gt(25)
    .sum()
)

np.int64(3)

In [139]:
#greater 25

#1 select the songs
#2 find their sum 

(songs[songs>25]).mean()

np.float64(108.33333333333333)

In [140]:
ser = df['Amount']

In [142]:
    ser

0        20.0
1       124.0
2         6.0
3         NaN
4         6.0
        ...  
7391     20.0
7392      5.0
7393    124.0
7394    124.0
7395    124.0
Name: Amount, Length: 7396, dtype: float64

In [143]:
ser.sum()

np.float64(263145.0)

In [144]:
ser.mean()

np.float64(35.63236289776574)

In [146]:
ser = pd.Series([78,165,744,475,214,367], name = 'count', index=['Glen', 'Mawuli', 'Portia', 'Rachael', 'Portia', 'Mavis' ])
ser

Glen        78
Mawuli     165
Portia     744
Rachael    475
Portia     214
Mavis      367
Name: count, dtype: int64

In [147]:
ser.loc['Rachael']

np.int64(475)

In [149]:
ser.loc[['Glen', 'Rachael', 'Mavis']]

Glen        78
Rachael    475
Mavis      367
Name: count, dtype: int64

In [152]:
ser[1]

C:\Users\Benedict.Hartmann\AppData\Local\Temp\ipykernel_23872\4267038266.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser[1]


np.int64(165)

In [ ]:
ser.

In [148]:
ser.loc['Portia']

Portia    744
Portia    214
Name: count, dtype: int64

In [155]:
type(ser.loc['Glen'])

numpy.int64

In [157]:
ser.gt(100)

Glen       False
Mawuli      True
Portia      True
Rachael     True
Portia      True
Mavis       True
Name: count, dtype: bool

In [159]:
ser.loc[(ser.gt(100))]

Mawuli     165
Portia     744
Rachael    475
Portia     214
Mavis      367
Name: count, dtype: int64

In [160]:
ser.iloc[[0,1,5]]

Glen       78
Mawuli    165
Mavis     367
Name: count, dtype: int64

In [161]:
songs.loc

In [167]:
songs.loc[0:3]

0    145
1    142
2     38
3     13
Name: counts, dtype: int64

In [168]:
songs.loc[1:6]

1    142
2     38
3     13
Name: counts, dtype: int64

In [169]:
ser.head(2)

Glen       78
Mawuli    165
Name: count, dtype: int64

In [170]:
ser.tail(3)

Rachael    475
Portia     214
Mavis      367
Name: count, dtype: int64

In [171]:
ser_2 = df['Amount']

In [166]:
songs.iloc[0:3]

0    145
1    142
2     38
Name: counts, dtype: int64

In [172]:
ser_2

0        20.0
1       124.0
2         6.0
3         NaN
4         6.0
        ...  
7391     20.0
7392      5.0
7393    124.0
7394    124.0
7395    124.0
Name: Amount, Length: 7396, dtype: float64

In [174]:
df = pd.read_csv('transaction_data.csv')
df

Item_Description  Amount Traffic_Source Session_Duration
0            Notebook    20.0         Direct            3,470
1       Google Hoodie   124.0         Direct              401
2      Greeting Cards     6.0    Paid Search            2,608
3                 NaN     NaN            NaN            2,130
4             Lanyard     6.0         Direct            3,517
...               ...     ...            ...              ...
7391  Android T-Shirt    20.0       Referral            2,223
7392  Google Stickers     5.0    Paid Search            3,101
7393    Google Hoodie   124.0         Direct            2,107
7394    Google Hoodie   124.0   Social Media              919
7395    Google Hoodie   124.0    Paid Search               11

[7396 rows x 4 columns]

In [175]:
#preview

df.head()

Item_Description  Amount Traffic_Source Session_Duration
0         Notebook    20.0         Direct            3,470
1    Google Hoodie   124.0         Direct              401
2   Greeting Cards     6.0    Paid Search            2,608
3              NaN     NaN            NaN            2,130
4          Lanyard     6.0         Direct            3,517

In [177]:
df['Amount']*0.5

0       10.0
1       62.0
2        3.0
3        NaN
4        3.0
        ... 
7391    10.0
7392     2.5
7393    62.0
7394    62.0
7395    62.0
Name: Amount, Length: 7396, dtype: float64

In [178]:
df['Amount'].mul(0.5)

0       10.0
1       62.0
2        3.0
3        NaN
4        3.0
        ... 
7391    10.0
7392     2.5
7393    62.0
7394    62.0
7395    62.0
Name: Amount, Length: 7396, dtype: float64

In [180]:
df['Amount'].mul(0.2)

0        4.0
1       24.8
2        1.2
3        NaN
4        1.2
        ... 
7391     4.0
7392     1.0
7393    24.8
7394    24.8
7395    24.8
Name: Amount, Length: 7396, dtype: float64

In [181]:
df['Amount'].add(df['Amount'].mul(0.25))

0        25.00
1       155.00
2         7.50
3          NaN
4         7.50
         ...  
7391     25.00
7392      6.25
7393    155.00
7394    155.00
7395    155.00
Name: Amount, Length: 7396, dtype: float64

In [190]:
df['disc_amount']=df['Amount']*0.5

In [191]:
df['Half_Price']=df['Amount'].mul(0.3)

df

Item_Description  Amount Traffic_Source Session_Duration  half_price  \
0            Notebook    20.0         Direct            3,470        10.0   
1       Google Hoodie   124.0         Direct              401        62.0   
2      Greeting Cards     6.0    Paid Search            2,608         3.0   
3                 NaN     NaN            NaN            2,130         NaN   
4             Lanyard     6.0         Direct            3,517         3.0   
...               ...     ...            ...              ...         ...   
7391  Android T-Shirt    20.0       Referral            2,223        10.0   
7392  Google Stickers     5.0    Paid Search            3,101         2.5   
7393    Google Hoodie   124.0         Direct            2,107        62.0   
7394    Google Hoodie   124.0   Social Media              919        62.0   
7395    Google Hoodie   124.0    Paid Search               11        62.0   

      Half_Price  disc_amount  
0            6.0         10.0  
1           37.2         62.0  
2            1.8          3.0  
3            NaN          NaN  
4            1.8          3.0  
...          ...          ...  
7391         6.0         10.0  
7392         1.5          2.5  
7393        37.2         62.0  
7394        37.2         62.0  
7395        37.2         62.0  

[7396 rows x 7 columns]

In [192]:
(
    df
    .assign(sales_tax = df['Amount'].mul(0.15))
)

Item_Description  Amount Traffic_Source Session_Duration  half_price  \
0            Notebook    20.0         Direct            3,470        10.0   
1       Google Hoodie   124.0         Direct              401        62.0   
2      Greeting Cards     6.0    Paid Search            2,608         3.0   
3                 NaN     NaN            NaN            2,130         NaN   
4             Lanyard     6.0         Direct            3,517         3.0   
...               ...     ...            ...              ...         ...   
7391  Android T-Shirt    20.0       Referral            2,223        10.0   
7392  Google Stickers     5.0    Paid Search            3,101         2.5   
7393    Google Hoodie   124.0         Direct            2,107        62.0   
7394    Google Hoodie   124.0   Social Media              919        62.0   
7395    Google Hoodie   124.0    Paid Search               11        62.0   

      Half_Price  disc_amount  sales_tax  
0            6.0         10.0       3.00  
1           37.2         62.0      18.60  
2            1.8          3.0       0.90  
3            NaN          NaN        NaN  
4            1.8          3.0       0.90  
...          ...          ...        ...  
7391         6.0         10.0       3.00  
7392         1.5          2.5       0.75  
7393        37.2         62.0      18.60  
7394        37.2         62.0      18.60  
7395        37.2         62.0      18.60  

[7396 rows x 8 columns]

In [203]:
(
    df
    .assign(sales_tax = df['Amount'].mul(0.15))
)

Item_Description  Amount Traffic_Source Session_Duration  half_price  \
0            Notebook    20.0         Direct            3,470        10.0   
1       Google Hoodie   124.0         Direct              401        62.0   
2      Greeting Cards     6.0    Paid Search            2,608         3.0   
3                 NaN     NaN            NaN            2,130         NaN   
4             Lanyard     6.0         Direct            3,517         3.0   
...               ...     ...            ...              ...         ...   
7391  Android T-Shirt    20.0       Referral            2,223        10.0   
7392  Google Stickers     5.0    Paid Search            3,101         2.5   
7393    Google Hoodie   124.0         Direct            2,107        62.0   
7394    Google Hoodie   124.0   Social Media              919        62.0   
7395    Google Hoodie   124.0    Paid Search               11        62.0   

      Half_Price  disc_amount  sales_tax  
0            6.0         10.0       3.00  
1           37.2         62.0      18.60  
2            1.8          3.0       0.90  
3            NaN          NaN        NaN  
4            1.8          3.0       0.90  
...          ...          ...        ...  
7391         6.0         10.0       3.00  
7392         1.5          2.5       0.75  
7393        37.2         62.0      18.60  
7394        37.2         62.0      18.60  
7395        37.2         62.0      18.60  

[7396 rows x 8 columns]

In [206]:
df['sales_tax'] = df['Amount'].mul(0.15)

In [207]:
df.head()

Item_Description  Amount Traffic_Source Session_Duration  half_price  \
0         Notebook    20.0         Direct            3,470        10.0   
1    Google Hoodie   124.0         Direct              401        62.0   
2   Greeting Cards     6.0    Paid Search            2,608         3.0   
3              NaN     NaN            NaN            2,130         NaN   
4          Lanyard     6.0         Direct            3,517         3.0   

   Half_Price  disc_amount  sales_tax  
0         6.0         10.0        3.0  
1        37.2         62.0       18.6  
2         1.8          3.0        0.9  
3         NaN          NaN        NaN  
4         1.8          3.0        0.9

In [208]:
df.head()

Item_Description  Amount Traffic_Source Session_Duration  half_price  \
0         Notebook    20.0         Direct            3,470        10.0   
1    Google Hoodie   124.0         Direct              401        62.0   
2   Greeting Cards     6.0    Paid Search            2,608         3.0   
3              NaN     NaN            NaN            2,130         NaN   
4          Lanyard     6.0         Direct            3,517         3.0   

   Half_Price  disc_amount  sales_tax  
0         6.0         10.0        3.0  
1        37.2         62.0       18.6  
2         1.8          3.0        0.9  
3         NaN          NaN        NaN  
4         1.8          3.0        0.9

In [209]:
(   
    df['Amount']
    .sum()
)

np.float64(263145.0)

In [210]:
df.describe()

Amount   half_price   Half_Price  disc_amount    sales_tax
count  7385.000000  7385.000000  7385.000000  7385.000000  7385.000000
mean     35.632363    17.816181    10.689709    17.816181     5.344854
std      47.752892    23.876446    14.325868    23.876446     7.162934
min       5.000000     2.500000     1.500000     2.500000     0.750000
25%       5.000000     2.500000     1.500000     2.500000     0.750000
50%      10.000000     5.000000     3.000000     5.000000     1.500000
75%      20.000000    10.000000     6.000000    10.000000     3.000000
max     125.000000    62.500000    37.500000    62.500000    18.750000

In [211]:
(   
    df['sales_tax']
    .max()
)

np.float64(18.75)

In [221]:
(
    df
    .groupby(by='Traffic_Source')
    ['Amount'].sum()
    .sort_values(ascending=False)
)

Traffic_Source
Social Media      54901.0
Paid Search       54523.0
Organic Search    53262.0
Direct            52562.0
Referral          47891.0
Name: Amount, dtype: float64

In [228]:
(
    df
    .groupby(by='Item_Description')
    ['Amount'].sum()
    .sort_values(ascending=False)
)

Item_Description
Google Hoodie          112468.0
Backpack                49750.0
Puffer Vest             46230.0
Google Stickers         12930.0
Notebook                 9240.0
Android T-Shirt          8820.0
Canvas Tote              7830.0
YouTube Cap              5895.0
Google Water Bottle      4540.0
Lanyard                  2724.0
Greeting Cards           2712.0
Name: Amount, dtype: float64

In [229]:
(
    df
    .value_counts('Item_Description')

)

Item_Description
Google Stickers        2586
Google Hoodie           907
Notebook                462
Lanyard                 454
Google Water Bottle     454
Greeting Cards          452
Android T-Shirt         441
Canvas Tote             435
Puffer Vest             402
Backpack                398
YouTube Cap             393
Name: count, dtype: int64

In [230]:
df['sales_tax']

0        3.00
1       18.60
2        0.90
3         NaN
4        0.90
        ...  
7391     3.00
7392     0.75
7393    18.60
7394    18.60
7395    18.60
Name: sales_tax, Length: 7396, dtype: float64

In [231]:
df[['sales_tax', 'half_price']]

sales_tax  half_price
0          3.00        10.0
1         18.60        62.0
2          0.90         3.0
3           NaN         NaN
4          0.90         3.0
...         ...         ...
7391       3.00        10.0
7392       0.75         2.5
7393      18.60        62.0
7394      18.60        62.0
7395      18.60        62.0

[7396 rows x 2 columns]

In [232]:
df[['sales_tax', 'Amount', 'Traffic_Source']]

sales_tax  Amount Traffic_Source
0          3.00    20.0         Direct
1         18.60   124.0         Direct
2          0.90     6.0    Paid Search
3           NaN     NaN            NaN
4          0.90     6.0         Direct
...         ...     ...            ...
7391       3.00    20.0       Referral
7392       0.75     5.0    Paid Search
7393      18.60   124.0         Direct
7394      18.60   124.0   Social Media
7395      18.60   124.0    Paid Search

[7396 rows x 3 columns]

In [233]:
##Using loc for filterung



In [235]:
df.loc[(df['Amount'] <40)]

Item_Description  Amount Traffic_Source Session_Duration  half_price  \
0            Notebook    20.0         Direct            3,470        10.0   
2      Greeting Cards     6.0    Paid Search            2,608         3.0   
4             Lanyard     6.0         Direct            3,517         3.0   
5     Google Stickers     5.0    Paid Search              706         2.5   
7     Google Stickers     5.0    Paid Search            1,728         2.5   
...               ...     ...            ...              ...         ...   
7388         Notebook    20.0   Social Media            1,308        10.0   
7389  Google Stickers     5.0         Direct            3,008         2.5   
7390  Google Stickers     5.0         Direct            1,502         2.5   
7391  Android T-Shirt    20.0       Referral            2,223        10.0   
7392  Google Stickers     5.0    Paid Search            3,101         2.5   

      Half_Price  disc_amount  sales_tax  
0            6.0         10.0       3.00  
2            1.8          3.0       0.90  
4            1.8          3.0       0.90  
5            1.5          2.5       0.75  
7            1.5          2.5       0.75  
...          ...          ...        ...  
7388         6.0         10.0       3.00  
7389         1.5          2.5       0.75  
7390         1.5          2.5       0.75  
7391         6.0         10.0       3.00  
7392         1.5          2.5       0.75  

[5678 rows x 8 columns]

In [236]:
df['Amount']<40

0        True
1       False
2        True
3       False
4        True
        ...  
7391     True
7392     True
7393    False
7394    False
7395    False
Name: Amount, Length: 7396, dtype: bool

In [240]:
mask = df['Amount'] == 6 
df.loc[mask]

Item_Description  Amount Traffic_Source Session_Duration  half_price  \
2      Greeting Cards     6.0    Paid Search            2,608         3.0   
4             Lanyard     6.0         Direct            3,517         3.0   
26     Greeting Cards     6.0    Paid Search            1,939         3.0   
28            Lanyard     6.0         Direct            1,380         3.0   
29            Lanyard     6.0    Paid Search              778         3.0   
...               ...     ...            ...              ...         ...   
7344   Greeting Cards     6.0       Referral            1,143         3.0   
7350   Greeting Cards     6.0    Paid Search            2,079         3.0   
7357          Lanyard     6.0       Referral            3,354         3.0   
7361   Greeting Cards     6.0         Direct            1,264         3.0   
7373   Greeting Cards     6.0       Referral            2,085         3.0   

      Half_Price  disc_amount  sales_tax  
2            1.8          3.0        0.9  
4            1.8          3.0        0.9  
26           1.8          3.0        0.9  
28           1.8          3.0        0.9  
29           1.8          3.0        0.9  
...          ...          ...        ...  
7344         1.8          3.0        0.9  
7350         1.8          3.0        0.9  
7357         1.8          3.0        0.9  
7361         1.8          3.0        0.9  
7373         1.8          3.0        0.9  

[907 rows x 8 columns]

In [243]:
# item descripoton and traffic sorice for itemns witg amount == 6 


df.loc[(df['Amount']==6), ['Item_Description', 'Traffic_Source', 'Amount']]

Item_Description Traffic_Source  Amount
2      Greeting Cards    Paid Search     6.0
4             Lanyard         Direct     6.0
26     Greeting Cards    Paid Search     6.0
28            Lanyard         Direct     6.0
29            Lanyard    Paid Search     6.0
...               ...            ...     ...
7344   Greeting Cards       Referral     6.0
7350   Greeting Cards    Paid Search     6.0
7357          Lanyard       Referral     6.0
7361   Greeting Cards         Direct     6.0
7373   Greeting Cards       Referral     6.0

[907 rows x 3 columns]

In [247]:
mask = df['Traffic_Source'] == 'Paid Search'

maskdf.loc[(mask), ['Amount', 'sales_tax']]

Amount  sales_tax
2        6.0       0.90
5        5.0       0.75
7        5.0       0.75
11     124.0      18.60
15      18.0       2.70
...      ...        ...
7359    10.0       1.50
7379   124.0      18.60
7385     5.0       0.75
7392     5.0       0.75
7395   124.0      18.60

[1501 rows x 2 columns]

In [257]:
mask = (df['Traffic_Source'] == 'Paid Search') & (df['Amount'] == 6) & (df['Item_Description'] == 'Lanyard' )


df.loc[mask, ['Amount'],].sum()

Amount    552.0
dtype: float64